import { Seed } from "./models/seed";

export class TestData {
  public TEAMS: Seed[] = [
    { school_id: 1 , school_name:  'Alabama', bracket_id: 1, overall_seed_number: 1, id:  1, seed_number:  1  },
    { school_id: 2 , school_name:  'Houston', bracket_id: 1 , overall_seed_number: 2, id: 2, seed_number: 2 },
    { school_id: 3 , school_name:  'Team 3',  bracket_id: 1 , overall_seed_number: 3, id: 3, seed_number: 3 },
    { school_id: 4 , school_name:  'Team 4',  bracket_id: 1 , overall_seed_number: 4, id: 4, seed_number: 4 },
    { school_id: 5 , school_name:  'Team 5',  bracket_id: 1 , overall_seed_number: 5, id: 5, seed_number: 5 },
    { school_id: 6 , school_name:  'Team 6',  bracket_id: 1 , overall_seed_number: 6, id: 6, seed_number: 6 },
    { school_id: 7 , school_name:  'Team 7',  bracket_id: 1 , overall_seed_number: 7, id: 7, seed_number: 7 },
    { school_id: 8 , school_name:  'Team 8',  bracket_id: 1 , overall_seed_number: 8, id: 8, seed_number: 8 },
    { school_id: 9 , school_name:  'Team 9',  bracket_id: 1 , overall_seed_number: 9, id: 9, seed_number: 9 },
    { school_id: 10, school_name: 'Team 10', bracket_id: 1 , overall_seed_number: 10, id: 10, seed_number: 10 },
    { school_id: 11, school_name: 'Team 11', bracket_id: 1 , overall_seed_number: 11, id: 11, seed_number: 11 },
    { school_id: 12, school_name: 'Team 12', bracket_id: 1 , overall_seed_number: 12, id: 12, seed_number: 12 },
    { school_id: 13, school_name: 'Team 13', bracket_id: 1 , overall_seed_number: 13, id: 13, seed_number: 13 },
    { school_id: 14, school_name: 'Team 14', bracket_id: 1 , overall_seed_number: 14, id: 14, seed_number: 14 },
    { school_id: 15, school_name: 'Team 15', bracket_id: 1 , overall_seed_number: 15, id: 15, seed_number: 15 },
    { school_id: 16, school_name: 'Team 16', bracket_id: 1 , overall_seed_number: 16, id: 16, seed_number: 16 },
    { school_id: 17, school_name: 'Team 17', bracket_id: 2 , overall_seed_number: 17, id: 17, seed_number: 1  },
    { school_id: 18, school_name: 'Team 18', bracket_id: 2 , overall_seed_number: 18, id: 18, seed_number: 2  },
    { school_id: 19, school_name: 'Team 19', bracket_id: 2 , overall_seed_number: 19, id: 19, seed_number: 3  },
    { school_id: 20, school_name: 'Team 20', bracket_id: 2 , overall_seed_number: 20, id: 20, seed_number:  4 },
    { school_id: 21, school_name: 'Team 21', bracket_id: 2 , overall_seed_number: 21, id: 21, seed_number:  5 },
    { school_id: 22, school_name: 'Team 22', bracket_id: 2 , overall_seed_number: 22, id: 22, seed_number:  6 },
    { school_id: 23, school_name: 'Team 23', bracket_id: 2 , overall_seed_number: 23, id: 23, seed_number:  7 },
    { school_id: 24, school_name: 'Team 24', bracket_id: 2 , overall_seed_number: 24, id: 24, seed_number:  8 },
    { school_id: 25, school_name: 'Team 25', bracket_id: 2 , overall_seed_number: 25, id: 25, seed_number:  9 },
    { school_id: 26, school_name: 'Team 26', bracket_id: 2 , overall_seed_number: 26, id: 26, seed_number:  10},
    { school_id: 27, school_name: 'Team 27', bracket_id: 2 , overall_seed_number: 27, id: 27, seed_number:  11},
    { school_id: 28, school_name: 'Team 28', bracket_id: 2 , overall_seed_number: 28, id: 28, seed_number:  12},
    { school_id: 29, school_name: 'Team 29', bracket_id: 2 , overall_seed_number: 29, id: 29, seed_number:  13},
    { school_id: 30, school_name: 'Team 30', bracket_id: 2 , overall_seed_number: 30, id: 30, seed_number:  14},
    { school_id: 31, school_name: 'Team 31', bracket_id: 2 , overall_seed_number: 31, id: 31, seed_number:  15},
    { school_id: 32, school_name: 'Team 32', bracket_id: 2 , overall_seed_number: 32, id: 32, seed_number:  16},
    { school_id: 33, school_name: 'Team 33', bracket_id: 3 , overall_seed_number: 33, id: 33, seed_number:  1 },
    { school_id: 34, school_name: 'Team 34', bracket_id: 3 , overall_seed_number: 34, id: 34, seed_number:  2 },
    { school_id: 35, school_name: 'Team 35', bracket_id: 3 , overall_seed_number: 35, id: 35, seed_number:  3 },
    { school_id: 36, school_name: 'Team 36', bracket_id: 3 , overall_seed_number: 36, id: 36, seed_number:  4 },
    { school_id: 37, school_name: 'Team 37', bracket_id: 3 , overall_seed_number: 37, id: 37, seed_number:  5 },
    { school_id: 38, school_name: 'Team 38', bracket_id: 3 , overall_seed_number: 38, id: 38, seed_number:  6 },
    { school_id: 39, school_name: 'Team 39', bracket_id: 3 , overall_seed_number: 39, id: 39, seed_number:  7 },
    { school_id: 40, school_name: 'Team 40', bracket_id: 3 , overall_seed_number: 40, id: 40, seed_number:  8 },
    { school_id: 41, school_name: 'Team 41', bracket_id: 3 , overall_seed_number: 41, id: 41, seed_number:  9 },
    { school_id: 42, school_name: 'Team 42', bracket_id: 3 , overall_seed_number: 42, id: 42, seed_number:  10},
    { school_id: 43, school_name: 'Team 43', bracket_id: 3 , overall_seed_number: 43, id: 43, seed_number:  11},
    { school_id: 44, school_name: 'Team 44', bracket_id: 3 , overall_seed_number: 44, id: 44, seed_number:  12},
    { school_id: 45, school_name: 'Team 45', bracket_id: 3 , overall_seed_number: 45, id: 45, seed_number:  13},
    { school_id: 46, school_name: 'Team 46', bracket_id: 3 , overall_seed_number: 46, id: 46, seed_number:  14},
    { school_id: 47, school_name: 'Team 47', bracket_id: 3 , overall_seed_number: 47, id: 47, seed_number:  15},
    { school_id: 48, school_name: 'Team 48', bracket_id: 3 , overall_seed_number: 48, id: 48, seed_number:  16},
    { school_id: 49, school_name: 'Team 49', bracket_id: 4 , overall_seed_number: 49, id: 49, seed_number:  1  },
    { school_id: 50, school_name: 'Team 50', bracket_id: 4 , overall_seed_number: 50, id: 50, seed_number:  2  },
    { school_id: 51, school_name: 'Team 51', bracket_id: 4 , overall_seed_number: 51, id: 51, seed_number:  3  },
    { school_id: 52, school_name: 'Team 52', bracket_id: 4 , overall_seed_number: 52, id: 52, seed_number:  4  },
    { school_id: 53, school_name: 'Team 53', bracket_id: 4 , overall_seed_number: 53, id: 53, seed_number:  5  },
    { school_id: 54, school_name: 'Team 54', bracket_id: 4 , overall_seed_number: 54, id: 54, seed_number:  6  },
    { school_id: 55, school_name: 'Team 55', bracket_id: 4 , overall_seed_number: 55, id: 55, seed_number:  7  },
    { school_id: 56, school_name: 'Team 56', bracket_id: 4 , overall_seed_number: 56, id: 56, seed_number:  8  },
    { school_id: 57, school_name: 'Team 57', bracket_id: 4 , overall_seed_number: 57, id: 57, seed_number:  9  },
    { school_id: 58, school_name: 'Team 58', bracket_id: 4 , overall_seed_number: 58, id: 58, seed_number:  10 },
    { school_id: 59, school_name: 'Team 59', bracket_id: 4 , overall_seed_number: 59, id: 59, seed_number:  11 },
    { school_id: 60, school_name: 'Team 20', bracket_id: 4 , overall_seed_number: 60, id: 60, seed_number:  12 },
    { school_id: 61, school_name: 'Team 61', bracket_id: 4 , overall_seed_number: 61, id: 61, seed_number:  13 },
    { school_id: 62, school_name: 'Team 62', bracket_id: 4 , overall_seed_number: 62, id: 62, seed_number:  14 },
    { school_id: 63, school_name: 'Team 63', bracket_id: 4 , overall_seed_number: 63, id: 63, seed_number:  15 },
    { school_id: 64, school_name: 'Team 64', bracket_id: 4 , overall_seed_number: 64, id: 64, seed_number:  16 },
    // play-in teams 
    { school_id: 65, school_name: 'Team 65', bracket_id: 5 , overall_seed_number: 65, id: 65, seed_number:  1 },
    { school_id: 66, school_name: 'Team 66', bracket_id: 5 , overall_seed_number: 66, id: 66, seed_number:  1 },
    { school_id: 67, school_name: 'Team 67', bracket_id: 5 , overall_seed_number: 67, id: 67, seed_number:  1 },
    { school_id: 68, school_name: 'Team 68', bracket_id: 5 , overall_seed_number: 68, id: 68, seed_number:  1 },
  ];
}
