import { Seed } from "./models/seed";

export class TestData {
  public TEAMS: Seed[] = [
    { schoolId: 1 , schoolName:  'Alabama', bracketId: 1, overallSeedNumber: 1, seedId:  1, seedNumber:  1  },
    { schoolId: 2 , schoolName:  'Houston', bracketId: 1 , overallSeedNumber: 2, seedId: 2, seedNumber: 2 },
    { schoolId: 3 , schoolName:  'Team 3',  bracketId: 1 , overallSeedNumber: 3, seedId: 3, seedNumber: 3 },
    { schoolId: 4 , schoolName:  'Team 4',  bracketId: 1 , overallSeedNumber: 4, seedId: 4, seedNumber: 4 },
    { schoolId: 5 , schoolName:  'Team 5',  bracketId: 1 , overallSeedNumber: 5, seedId: 5, seedNumber: 5 },
    { schoolId: 6 , schoolName:  'Team 6',  bracketId: 1 , overallSeedNumber: 6, seedId: 6, seedNumber: 6 },
    { schoolId: 7 , schoolName:  'Team 7',  bracketId: 1 , overallSeedNumber: 7, seedId: 7, seedNumber: 7 },
    { schoolId: 8 , schoolName:  'Team 8',  bracketId: 1 , overallSeedNumber: 8, seedId: 8, seedNumber: 8 },
    { schoolId: 9 , schoolName:  'Team 9',  bracketId: 1 , overallSeedNumber: 9, seedId: 9, seedNumber: 9 },
    { schoolId: 10, schoolName: 'Team 10', bracketId: 1 , overallSeedNumber: 10, seedId: 10, seedNumber: 10 },
    { schoolId: 11, schoolName: 'Team 11', bracketId: 1 , overallSeedNumber: 11, seedId: 11, seedNumber: 11 },
    { schoolId: 12, schoolName: 'Team 12', bracketId: 1 , overallSeedNumber: 12, seedId: 12, seedNumber: 12 },
    { schoolId: 13, schoolName: 'Team 13', bracketId: 1 , overallSeedNumber: 13, seedId: 13, seedNumber: 13 },
    { schoolId: 14, schoolName: 'Team 14', bracketId: 1 , overallSeedNumber: 14, seedId: 14, seedNumber: 14 },
    { schoolId: 15, schoolName: 'Team 15', bracketId: 1 , overallSeedNumber: 15, seedId: 15, seedNumber: 15 },
    { schoolId: 16, schoolName: 'Team 16', bracketId: 1 , overallSeedNumber: 16, seedId: 16, seedNumber: 16 },
    { schoolId: 17, schoolName: 'Team 17', bracketId: 2 , overallSeedNumber: 17, seedId: 17, seedNumber: 1  },
    { schoolId: 18, schoolName: 'Team 18', bracketId: 2 , overallSeedNumber: 18, seedId: 18, seedNumber: 2  },
    { schoolId: 19, schoolName: 'Team 19', bracketId: 2 , overallSeedNumber: 19, seedId: 19, seedNumber: 3  },
    { schoolId: 20, schoolName: 'Team 20', bracketId: 2 , overallSeedNumber: 20, seedId: 20, seedNumber:  4 },
    { schoolId: 21, schoolName: 'Team 21', bracketId: 2 , overallSeedNumber: 21, seedId: 21, seedNumber:  5 },
    { schoolId: 22, schoolName: 'Team 22', bracketId: 2 , overallSeedNumber: 22, seedId: 22, seedNumber:  6 },
    { schoolId: 23, schoolName: 'Team 23', bracketId: 2 , overallSeedNumber: 23, seedId: 23, seedNumber:  7 },
    { schoolId: 24, schoolName: 'Team 24', bracketId: 2 , overallSeedNumber: 24, seedId: 24, seedNumber:  8 },
    { schoolId: 25, schoolName: 'Team 25', bracketId: 2 , overallSeedNumber: 25, seedId: 25, seedNumber:  9 },
    { schoolId: 26, schoolName: 'Team 26', bracketId: 2 , overallSeedNumber: 26, seedId: 26, seedNumber:  10},
    { schoolId: 27, schoolName: 'Team 27', bracketId: 2 , overallSeedNumber: 27, seedId: 27, seedNumber:  11},
    { schoolId: 28, schoolName: 'Team 28', bracketId: 2 , overallSeedNumber: 28, seedId: 28, seedNumber:  12},
    { schoolId: 29, schoolName: 'Team 29', bracketId: 2 , overallSeedNumber: 29, seedId: 29, seedNumber:  13},
    { schoolId: 30, schoolName: 'Team 30', bracketId: 2 , overallSeedNumber: 30, seedId: 30, seedNumber:  14},
    { schoolId: 31, schoolName: 'Team 31', bracketId: 2 , overallSeedNumber: 31, seedId: 31, seedNumber:  15},
    { schoolId: 32, schoolName: 'Team 32', bracketId: 2 , overallSeedNumber: 32, seedId: 32, seedNumber:  16},
    { schoolId: 33, schoolName: 'Team 33', bracketId: 3 , overallSeedNumber: 33, seedId: 33, seedNumber:  1 },
    { schoolId: 34, schoolName: 'Team 34', bracketId: 3 , overallSeedNumber: 34, seedId: 34, seedNumber:  2 },
    { schoolId: 35, schoolName: 'Team 35', bracketId: 3 , overallSeedNumber: 35, seedId: 35, seedNumber:  3 },
    { schoolId: 36, schoolName: 'Team 36', bracketId: 3 , overallSeedNumber: 36, seedId: 36, seedNumber:  4 },
    { schoolId: 37, schoolName: 'Team 37', bracketId: 3 , overallSeedNumber: 37, seedId: 37, seedNumber:  5 },
    { schoolId: 38, schoolName: 'Team 38', bracketId: 3 , overallSeedNumber: 38, seedId: 38, seedNumber:  6 },
    { schoolId: 39, schoolName: 'Team 39', bracketId: 3 , overallSeedNumber: 39, seedId: 39, seedNumber:  7 },
    { schoolId: 40, schoolName: 'Team 40', bracketId: 3 , overallSeedNumber: 40, seedId: 40, seedNumber:  8 },
    { schoolId: 41, schoolName: 'Team 41', bracketId: 3 , overallSeedNumber: 41, seedId: 41, seedNumber:  9 },
    { schoolId: 42, schoolName: 'Team 42', bracketId: 3 , overallSeedNumber: 42, seedId: 42, seedNumber:  10},
    { schoolId: 43, schoolName: 'Team 43', bracketId: 3 , overallSeedNumber: 43, seedId: 43, seedNumber:  11},
    { schoolId: 44, schoolName: 'Team 44', bracketId: 3 , overallSeedNumber: 44, seedId: 44, seedNumber:  12},
    { schoolId: 45, schoolName: 'Team 45', bracketId: 3 , overallSeedNumber: 45, seedId: 45, seedNumber:  13},
    { schoolId: 46, schoolName: 'Team 46', bracketId: 3 , overallSeedNumber: 46, seedId: 46, seedNumber:  14},
    { schoolId: 47, schoolName: 'Team 47', bracketId: 3 , overallSeedNumber: 47, seedId: 47, seedNumber:  15},
    { schoolId: 48, schoolName: 'Team 48', bracketId: 3 , overallSeedNumber: 48, seedId: 48, seedNumber:  16},
    { schoolId: 49, schoolName: 'Team 49', bracketId: 4 , overallSeedNumber: 49, seedId: 49, seedNumber:  1  },
    { schoolId: 50, schoolName: 'Team 50', bracketId: 4 , overallSeedNumber: 50, seedId: 50, seedNumber:  2  },
    { schoolId: 51, schoolName: 'Team 51', bracketId: 4 , overallSeedNumber: 51, seedId: 51, seedNumber:  3  },
    { schoolId: 52, schoolName: 'Team 52', bracketId: 4 , overallSeedNumber: 52, seedId: 52, seedNumber:  4  },
    { schoolId: 53, schoolName: 'Team 53', bracketId: 4 , overallSeedNumber: 53, seedId: 53, seedNumber:  5  },
    { schoolId: 54, schoolName: 'Team 54', bracketId: 4 , overallSeedNumber: 54, seedId: 54, seedNumber:  6  },
    { schoolId: 55, schoolName: 'Team 55', bracketId: 4 , overallSeedNumber: 55, seedId: 55, seedNumber:  7  },
    { schoolId: 56, schoolName: 'Team 56', bracketId: 4 , overallSeedNumber: 56, seedId: 56, seedNumber:  8  },
    { schoolId: 57, schoolName: 'Team 57', bracketId: 4 , overallSeedNumber: 57, seedId: 57, seedNumber:  9  },
    { schoolId: 58, schoolName: 'Team 58', bracketId: 4 , overallSeedNumber: 58, seedId: 58, seedNumber:  10 },
    { schoolId: 59, schoolName: 'Team 59', bracketId: 4 , overallSeedNumber: 59, seedId: 59, seedNumber:  11 },
    { schoolId: 60, schoolName: 'Team 20', bracketId: 4 , overallSeedNumber: 60, seedId: 60, seedNumber:  12 },
    { schoolId: 61, schoolName: 'Team 61', bracketId: 4 , overallSeedNumber: 61, seedId: 61, seedNumber:  13 },
    { schoolId: 62, schoolName: 'Team 62', bracketId: 4 , overallSeedNumber: 62, seedId: 62, seedNumber:  14 },
    { schoolId: 63, schoolName: 'Team 63', bracketId: 4 , overallSeedNumber: 63, seedId: 63, seedNumber:  15 },
    { schoolId: 64, schoolName: 'Team 64', bracketId: 4 , overallSeedNumber: 64, seedId: 64, seedNumber:  16 },
    // play-in teams 
    { schoolId: 65, schoolName: 'Team 65', bracketId: 5 , overallSeedNumber: 65, seedId: 65, seedNumber:  1 },
    { schoolId: 66, schoolName: 'Team 66', bracketId: 5 , overallSeedNumber: 66, seedId: 66, seedNumber:  1 },
    { schoolId: 67, schoolName: 'Team 67', bracketId: 5 , overallSeedNumber: 67, seedId: 67, seedNumber:  1 },
    { schoolId: 68, schoolName: 'Team 68', bracketId: 5 , overallSeedNumber: 68, seedId: 68, seedNumber:  1 },
  ];
}
