insert into bc_school
(name, conference, city, state)
values
('Abilene Christian','Western Athletic Conference','Abilene','Texas'),
('Akron','Mid-American Conference','Akron','Ohio'),
('Alabama','Southeastern Conference','Tuscaloosa','Alabama'),
('Alabama – Birmingham','Conference USA','Birmingham','Alabama'),
('Alabama A&M','Southwestern Athletic Conference','Normal','Alabama'),
('Alabama State','Southwestern Athletic Conference','Montgomery','Alabama'),
('Alcorn State','Southwestern Athletic Conference','Alcorn','Mississippi'),
('American','Patriot League','Washington','District Of Columbia'),
('Appalachian State','Sun Belt Conference','Boone','North Carolina'),
('Arizona','Pacific-12 Conference','Tucson','Arizona'),
('Arizona State','Pacific-12 Conference','Tempe','Arizona'),
('Arkansas','Southeastern Conference','Fayetteville','Arkansas'),
('Arkansas at Little Rock','Sun Belt Conference','Little Rock','Arkansas'),
('Arkansas at Pine Bluff','Southwestern Athletic Conference','Pine Bluff','Arkansas'),
('Arkansas State','Sun Belt Conference','Jonesboro','Arkansas'),
('Auburn','Southeastern Conference','Auburn','Alabama'),
('Austin Peay State','ASUN Conference','Clarksville','Tennessee'),
('Ball State','Mid-American Conference','Muncie','Indiana'),
('Baylor','Big 12 Conference','Waco','Texas'),
('Bellarmine','ASUN Conference','Louisville','Kentucky'),
('Belmont','Missouri Valley Conference','Nashville','Tennessee'),
('Bethune-Cookman','Southwestern Athletic Conference','Daytona Beach','Florida'),
('Boise State','Mountain West Conference','Boise','Idaho'),
('Boston','Atlantic Coast Conference','Chestnut Hill','Massachusetts'),
('Boston','Patriot League','Boston','Massachusetts'),
('Bowling Green State','Mid-American Conference','Bowling Green','Ohio'),
('Bradley','Missouri Valley Conference','Peoria','Illinois'),
('Brigham Young','West Coast Conference','Provo','Utah'),
('Brown','Ivy League','Providence','Rhode Island'),
('Bryant','American East Conference','Smithfield','Rhode Island'),
('Bucknell','Patriot League','Lewisburg','Pennsylvania'),
('Butler','Big East Conference','Indianapolis','Indiana'),
('California – Berkeley','Pacific-12 Conference','Berkeley','California'),
('California – Davis','Big Sky Conference','Davis','California'),
('California – Irvine','Big West Conference','Irvine','California'),
('California – Los Angeles – UCLA','Pacific-12 Conference','Los Angeles','California'),
('California – Riverside','Big West Conference','Riverside','California'),
('California – San Diego','Big West Conference','La Jolla','California'),
('California – Santa Barbara','Big West Conference','Santa Barbara','California'),
('California Baptist','Western Athletic Conference','Riverside','California'),
('California Polytechnic State – San Luis Obispo','Big Sky Conference','San Luis Obispo','California'),
('California State – Bakersfield','Big West Conference','Bakersfield','California'),
('California State – Fresno','Mountain West Conference','Fresno','California'),
('California State – Fullerton','Big West Conference','Fullerton','California'),
('California State – Long Beach','Big West Conference','Long Beach','California'),
('California State – Northridge','Big West Conference','Northridge','California'),
('California State – Sacramento','Big Sky Conference','Sacramento','California'),
('Campbell','Big South Conference','Buies Creek','North Carolina'),
('Canisius','Metro Atlantic Athletic Conference','Buffalo','New York'),
('Central Arkansas','Southland Conference','Conway','Arkansas'),
('Central Connecticut State','Northeast Conference','New Britain','Connecticut'),
('Central Florida','American Athletic Conference','Orlando','Florida'),
('Central Michigan','Mid-American Conference','Mount Pleasant','Michigan'),
('Charleston Southern','Big South Conference','Charleston','South Carolina'),
('Chicago State','Ohio Valley Conference','Chicago','Illinois'),
('Cincinnati','American Athletic Conference','Cincinnati','Ohio'),
('Clemson','Atlantic Coast Conference','Clemson','South Carolina'),
('Cleveland State','Horizon League','Cleveland','Ohio'),
('Coastal Carolina','Sun Belt Conference','Conway','South Carolina'),
('Colgate','Patriot League','Hamilton','New York'),
('College of Charleston','Colonial Athletic Association','Charleston','South Carolina'),
('Colorado – Boulder','Pacific-12 Conference','Boulder','Colorado'),
('Colorado State','Mountain West Conference','Fort Collins','Colorado'),
('Columbia','Ivy League','New York','New York'),
('Connecticut','Big East Conference','Storrs','Connecticut'),
('Coppin State','Mid-Eastern Athletic Conference','Baltimore','Maryland'),
('Cornell','Ivy League','Ithaca','New York'),
('Creighton','Big East Conference','Omaha','Nebraska'),
('Dartmouth','Ivy League','Hanover','New Hampshire'),
('Davidson','Atlantic 10 conference','Davidson','North Carolina'),
('Dayton','Atlantic 10 Conference','Dayton','Ohio'),
('Delaware','Colonial Athletic Association','Newark','Delaware'),
('Delaware State','Mid-Eastern Athletic Conference','Dover','Delaware'),
('Denver','The Summit League','Denver','Colorado'),
('DePaul','Big East Conference','Chicago','Illinois'),
('Detroit Mercy','Horizon League','Detroit','Michigan'),
('Drake','Misouri Valley Conference','Des Moines','Iowa'),
('Drexel','Colonial Athletic Association','Philadelphia','Pennsylvania'),
('Duke','Atlantic Coast Conference','Durham','North Carolina'),
('Duquesne','Altantic 10 Conference','Pittsburgh','Pennsylvania'),
('East Carolina','American Athletic Conference','Greenville','North Carolina'),
('East Tennessee State','Southern Conference','Johnson City','Tennessee'),
('Eastern Illinois','Ohio Valley Conference','Charleston','Illinois'),
('Eastern Kentucky','Asun Conference','Richmond','Kentucky'),
('Eastern Michigan','Mid-American Conference','Ypsilanti','Michigan'),
('Eastern Washington','Big Sky Conference','Cheney','Washington'),
('Elon','Colonial Athletic Association','Elon','North Carolina'),
('Evansville','Missouri Valley Conference','Evansville','Indiana'),
('Fairfield','Metro Atlantic Athletic Conference','Fairfield','Connecticut'),
('Fairleigh Dickinson','Northeast Conference','Teaneck','New Jersey'),
('Florida','Southeastern Conference','Gainesville','Florida'),
('Florida A&M','Southwestern Athletic Conference','Tallahassee','Florida'),
('Florida Atlantic','The american athletic Conference','Boca Raton','Florida'),
('Florida Gulf Coast','Atlantic Sun Conference','Fort Myers','Florida'),
('Florida International','Conference USA','Miami','Florida'),
('Florida State','Atlantic Coast Conference','Tallahassee','Florida'),
('Fordham','Patriot League','Bronx','New York'),
('Furman','Southern Conference','Greenville','South Carolina'),
('Gardner-Webb','Big South Conference','Boiling Springs','North Carolina'),
('George Mason','Atlantic 10 Conference','Fairfax','Virginia'),
('George Washington','Atlantic 10 Conference','Washington','District Of Columbia'),
('Georgetown','Patriot League','Washington','District Of Columbia'),
('Georgia','Southeastern Conference','Athens','Georgia'),
('Georgia Southern','Sun Belt Conference','Statesboro','Georgia'),
('Georgia State','Sun Belt Conference','Atlanta','Georgia'),
('Georgia Tech','Atlantic Coast Conference','Atlanta','Georgia'),
('Gonzaga','West Coast Conference','Spokane','Washington'),
('Grambling State','Southwestern Athletic Conference','Grambling','Louisiana'),
('Grand Canyon','Western Athletic Conference','Phoenix','Arizona'),
('Hamline','Minnesota Intercollegiate Athletic Conference','Saint Paul','Minnesota'),
('Hampton','Colonial Athletic Association','Hampton','Virginia'),
('Harvard','Ivy League','Cambridge','Massachusetts'),
('Hawaii at Manoa','Mountain West Conference','Honolulu','Hawaii'),
('High Point','Big South Conference','High Point','North Carolina'),
('Hofstra','Colonial Athletic Association','Hempstead','New York'),
('Holy Cross','Patriot League','Worcester','Massachusetts'),
('Houston','American Athletic Conference','Houston','Texas'),
('Houston Christian','Southland Conference','Houston','Texas'),
('Howard','Mid-Eastern Athletic Conference','Washington','District Of Columbia'),
('Idaho','Big Sky Conference','Moscow','Idaho'),
('Idaho State','Big Sky Conference','Pocatello','Idaho'),
('Illinois','Big Ten Conference','Champaign','Illinois'),
('Illinois at Chicago','Missouri Valley Conference','Chicago','Illinois'),
('Illinois State','Missouri Valley Conference','Normal','Illinois'),
('Incarnate Word','Southland Conference','San Antonio','Texas'),
('Indiana','Big Ten Conference','Bloomington','Indiana'),
('Indiana State','Missouri Valley Conference','Terre Haute','Indiana'),
('Indiana-Purdue – Indianapolis (IUPUI)','Horizon League','Indianapolis','Indiana'),
('Iona','Metro Atlantic Athletic Conference','New Rochelle','New York'),
('Iowa','Big Ten Conference','Iowa City','Iowa'),
('Iowa State','Big 12 Conference','Ames','Iowa'),
('Jackson State','Southwestern Athletic Conference','Jackson','Mississippi'),
('Jacksonville','Atlantic Sun Conference','Jacksonville','Florida'),
('Jacksonville State','ASUN Conference','Jacksonville','Alabama'),
('James Madison','Colonial Athletic Association','Harrisonburg','Virginia'),
('Kansas','Big 12 Conference','Lawrence','Kansas'),
('Kansas State','Big 12 Conference','Manhattan','Kansas'),
('Kennesaw State','Atlantic Sun Conference','Kennesaw','Georgia'),
('Kent State','Mid-American Conference','Kent','Ohio'),
('Kentucky','Southeastern Conference','Lexington','Kentucky'),
('La Salle','Atlantic 10 Conference','Philadelphia','Pennsylvania'),
('Lafayette','Patriot League','Easton','Pennsylvania'),
('Lamar','Southland Conference','Beaumont','Texas'),
('Lehigh','Patriot League','Bethlehem','Pennsylvania'),
('Liberty','Conference USA','Lynchburg','Virginia'),
('Lindenwood','Ohio Valley Conference','Saint Charles','Missouri'),
('Lipscomb','Atlantic Sun Conference','Nashville','Tennessee'),
('Long Island','Northeast Conference','Long Island','New York'),
('Longwood','Big South Conference','Farmville','Virginia'),
('Louisiana','Sun Belt Conference','Lafayette','Louisiana'),
('Louisiana – Monroe','Sun Belt Conference','Monroe','Louisiana'),
('Louisiana State (LSU)','Southeastern Conference','Baton Rouge','Louisiana'),
('Louisiana Tech','Conference USA','Ruston','Louisiana'),
('Louisville','Atlantic Coast Conference','Louisville','Kentucky'),
('Loyola Chicago','Atlantic 10 Conference','Chicago','Illinois'),
('Loyola Maryland','Patriot League','Baltimore','Maryland'),
('Loyola Marymount','West Coast Conference','Los Angeles','California'),
('Maine','America East Conference','Orono','Maine'),
('Manhattan','Metro Atlantic Athletic Conference','Riverdale','New York'),
('Marist','Metro Atlantic Athletic Conference','Poughkeepsie','New York'),
('Marquette','Big East Conference','Milwaukee','Wisconsin'),
('Marshall','Conference USA','Huntington','West Virginia'),
('Maryland','Big Ten Conference','College Park','Maryland'),
('Maryland – Baltimore County','America East Conference','Baltimore','Maryland'),
('Maryland Eastern Shore','Mid-Eastern Athletic Conference','Princess Anne','Maryland'),
('Massachusetts – Amherst','Atlantic 10 Conference','Amherst','Massachusetts'),
('Massachusetts – Lowell','America East Conference','Lowell','Massachusetts'),
('McNeese State','Southland Conference','Lake Charles','Louisiana'),
('Memphis','American Athletic Conference','Memphis','Tennessee'),
('Mercer','Southern Conference','Macon','Georgia'),
('Merrimack','Northeast Conference','North Andover','Massachusetts'),
('Miami','Mid-American Conference','Oxford','Ohio'),
('Miami','Atlantic Coast Conference','Coral Gables','Florida'),
('Michigan','Big Ten Conference','Ann Arbor','Michigan'),
('Michigan State','Big Ten Conference','East Lansing','Michigan'),
('Middle Tennessee State','Conference USA','Murfreesboro','Tennessee'),
('Minnesota','Big Ten Conference','Minneapolis','Minnesota'),
('Mississippi','Southeastern Conference','University','Mississippi'),
('Mississippi State','Southeastern Conference','Mississippi State','Mississippi'),
('Mississippi Valley State','Southwestern Athletic Conference','Itta Bena','Mississippi'),
('Missouri','Southeastern Conference','Columbia','Missouri'),
('Missouri – Kansas City','The Summit League','Kansas City','Missouri'),
('Missouri State','Missouri Valley Conference','Springfield','Missouri'),
('Monmouth','Mid-Eastern Athletic Conference','West Long Branch','New Jersey'),
('Montana','Big Sky Conference','Missoula','Montana'),
('Montana State','Big Sky Conference','Bozeman','Montana'),
('Morehead State','Ohio Valley Conference','Morehead','Kentucky'),
('Morgan State','Mid-Eastern Athletic Conference','Baltimore','Maryland'),
('Mount St. Mary''s','Metro Atlantic Athletic Conference','Emmitsburg','Maryland'),
('Murray State','Missouri Valley Conference','Murray','Kentucky'),
('Nebraska','Big Ten Conference','Lincoln','Nebraska'),
('Nebraska at Omaha','The Summit League','Omaha','Nebraska'),
('Nevada – Las Vegas','Mountain West Conference','Las Vegas','Nevada'),
('Nevada – Reno','Mountain West Conference','Reno','Nevada'),
('New Hampshire','American East Conference','Durham','New Hampshire'),
('New Jersey Institute of Technology','American East Conference','Newark','New Jersey'),
('New Mexico','Mountain West Conference','Albuquerque','New Mexico'),
('New Mexico State','Sun Belt Conference','Las Cruces','New Mexico'),
('New Orleans','Southland Conference','New Orleans','Louisiana'),
('Niagara','Metro Atlantic Athletic Conference','Niagara','New York'),
('Nicholls State','Southland Conference','Thibodaux','Louisiana'),
('Norfolk State','Mid-Eastern Athletic Conference','Norfolk','Virginia'),
('North Alabama','Gulf South Conference','Florence','Alabama'),
('North Carolina','Atlantic Coast Conference','Chapel Hill','North Carolina'),
('North Carolina – Greensboro','Southern Conference','Greensboro','North Carolina'),
('North Carolina – Wilmington','Colonial Athletic Association','Wilmington','North Carolina'),
('North Carolina A&T State','Mid-Eastern Athletic Conference','Greensboro','North Carolina'),
('North Carolina Asheville','Big South Conference','Asheville','North Carolina'),
('North Carolina at Charlotte','Conference USA','Charlotte','North Carolina'),
('North Carolina Central','Mid-Eastern Athletic Conference','Durham','North Carolina'),
('North Carolina State','Atlantic Coast Conference','Raleigh','North Carolina'),
('North Dakota','Big Sky Conference','Grand Forks','North Dakota'),
('North Dakota State','Summit League','Fargo','North Dakota'),
('North Florida','Atlantic Sun Conference','Jacksonville','Florida'),
('North Texas','Conference USA','Denton','Texas'),
('Northeastern','Colonial Athletic Association','Boston','Massachusetts'),
('Northern Arizona','Big Sky Conference','Flagstaff','Arizona'),
('Northern Colorado','Big Sky Conference','Greeley','Colorado'),
('Northern Illinois','Mid-American Conference','Dekalb','Illinois'),
('Northern Iowa','Missouri Valley Conference','Cedar Falls','Iowa'),
('Northern Kentucky','Horizon League','Highland Heights','Kentucky'),
('Northwestern','Big Ten Conference','Evanston','Illinois'),
('Northwestern State of Louisiana','Southland Conference','Natchitoches','Louisiana'),
('Notre Dame','Division I-A Independents','Notre Dame','Indiana'),
('Oakland','Horizon League','Rochester','Michigan'),
('Ohio','Mid-American Conference','Athens','Ohio'),
('Ohio State','Big Ten Conference','Columbus','Ohio'),
('Oklahoma','Big 12 Conference','Norman','Oklahoma'),
('Oklahoma State','Big 12 Conference','Stillwater','Oklahoma'),
('Old Dominion','Sunbelt Conference','Norfolk','Virginia'),
('Oral Roberts','The Summit League','Tulsa','Oklahoma'),
('Oregon','Pacific-12 Conference','Eugene','Oregon'),
('Oregon State','Pacific-12 Conference','Corvallis','Oregon'),
('Pacific','West Coast Conference','Stockton','California'),
('Penn','Ivy League','Philadelphia','Pennsylvania'),
('Penn State','Big Ten Conference','University Park','Pennsylvania'),
('Pepperdine','West Coast Conference','Malibu','California'),
('Pittsburgh','Atlantic Coast Conference','Pittsburgh','Pennsylvania'),
('Portland','West Coast Conference','Portland','Oregon'),
('Portland State','Big Sky Conference','Portland','Oregon'),
('Prairie View A & M','Southwestern Athletic Conference','Prairie View','Texas'),
('Presbyterian','Big South Conference','Clinton','South Carolina'),
('Princeton','Ivy League','Princeton','New Jersey'),
('Providence','Big East Conference','Providence','Rhode Island'),
('Purdue','Big Ten Conference','West Lafayette','Indiana'),
('Purdue – Fort Wayne','Horizon League','Fort Wayne','Indiana'),
('Queens of Charlotte','Atlantic Sun Conference','Charlotte','North Carolina'),
('Quinnipiac','Metro Atlantic Athletic Conference','Hamden','Connecticut'),
('Radford','Big South Conference','Radford','Virginia'),
('Rhode Island','Atlantic Ten Conference','Kingston','Rhode Island'),
('Rice','Conference USA','Houston','Texas'),
('Richmond','Atlantic 10 Conference','Richmond','Virginia'),
('Rider','Metro Atlantic Athletic Conference','Lawrenceville','New Jersey'),
('Robert Morris – Pennsylvania','Northeast Conference','Moon Township','Pennsylvania'),
('Rutgers','Big Ten Conference','Piscataway','New Jersey'),
('Sacred Heart','Northeast Conference','Fairfield','Connecticut'),
('Saint Francis','Northeast Conference','Loretto','Pennsylvania'),
('Saint Joseph''s','Atlantic 10 Conference','Philadelphia','Pennsylvania'),
('Saint Louis','Atlantic 10 Conference','St. Louis','Missouri'),
('Saint Mary''s of California','West Coast Conference','Moraga','California'),
('Saint Peter''s','Metro Atlantic Athletic Conference','Jersey City','New Jersey'),
('Sam Houston State','Western Athletic Conference','Huntsville','Texas'),
('Samford','Southern Conference','Birmingham','Alabama'),
('San Diego','West Coast Conference','San Diego','California'),
('San Diego State','Mountain West Conference','San Diego','California'),
('San Francisco','West Coast Conference','San Francisco','California'),
('San Jose State','Mountain West Conference','San Jose','California'),
('Santa Clara','West Coast Conference','Santa Clara','California'),
('Seattle','Western Athletic Conference','Seattle','Washington'),
('Seton Hall','Big East Conference','South Orange','New Jersey'),
('Siena','Metro Atlantic Athletic Conference','Loudonville','New York'),
('South Alabama','Sun Belt Conference','Mobile','Alabama'),
('South Carolina','Southeastern Conference','Columbia','South Carolina'),
('South Carolina – Upstate','Big South Conference','Spartanburg','South Carolina'),
('South Carolina State','Mid-Eastern Athletic Conference','Orangeburg','South Carolina'),
('South Dakota','The Summit League','Vermillion','South Dakota'),
('South Dakota State','Summit League Conference','Brookings','South Dakota'),
('South Florida','American Athletic Conference','Tampa','Florida'),
('Southeast Missouri State','Ohio Valley Conference','Cape Girardeau','Missouri'),
('Southeastern Louisiana','Southland Conference','Hammond','Louisiana'),
('Southern & A&M','Southwestern Athletic Conference','Baton Rouge','Louisiana'),
('Southern California','Pacific-12 Conference','Los Angeles','California'),
('Southern Illinois Carbondale','Missouri Valley Conference','Carbondale','Illinois'),
('Southern Illinois Edwardsville','Ohio Valley Conference','Edwardsville','Illinois'),
('Southern Methodist – SMU','American Athletic Conference','Dallas','Texas'),
('Southern Mississippi','Sun Belt Conference','Hattiesburg','Mississippi'),
('Southern Utah','Western Athletic Conference','Cedar City','Utah'),
('St. Bonaventure','Atlantic 10 Conference','Saint Bonaventure','New York'),
('St. Francis','Northeast Conference','Brooklyn Heights','New York'),
('St. John''s – New York','Big East Conference','Queens','New York'),
('St. Thomas – Minnesota','The Summit League','Saint Paul','Minnesota'),
('Stanford','Pacific-12 Conference','Stanford','California'),
('Stephen F Austin State','Western Conference','Nacogdoches','Texas'),
('Stetson','Metro Atlantic Athletic Conference','Deland','Florida'),
('Stonehill','Northeast Conference','Easton','Massachusetts'),
('SUNY at Albany','America East Conference','Albany','New York'),
('SUNY at Buffalo','Mid-American Conference','Buffalo','New York'),
('SUNY Binghamton','America East Conference','Vestal','New York'),
('SUNY Stony Brook','Colonial Athletic Association','Stony Brook','New York'),
('Syracuse','American Athletics Conference','Syracuse','New York'),
('Tarleton State','Western Athletic Conference','Stephenville','Texas'),
('Temple','American Athletic Conference','Philadelphia','Pennsylvania'),
('Tennessee','Southeastern Conference','Knoxville','Tennessee'),
('Tennessee – Chattanooga','Southern Conference','Chattanooga','Tennessee'),
('Tennessee – Martin','Ohio Valley Conference','Martin','Tennessee'),
('Tennessee State','Ohio Valley Conference','Nashville','Tennessee'),
('Texas – Arlington','Western Atlantic Conference','Arlington','Texas'),
('Texas – Arlington','Western Athletic Conference','Arlington','Texas'),
('Texas – Austin','Big 12 Conference','Austin','Texas'),
('Texas – El Paso','Conference USA','El Paso','Texas'),
('Texas – Rio Grande Valley','Western Athletic Conference','Edinburg','Texas'),
('Texas – San Antonio','Conference USA','San Antonio','Texas'),
('Texas A&M','Southeastern Conference','College Station','Texas'),
('Texas A&M – Commerce','Lone Star Conference','Commerce','Texas'),
('Texas A&M – Corpus Christi','Southland Conference','Corpus Christi','Texas'),
('Texas Christian','Big 12 Conference','Fort Worth','Texas'),
('Texas Southern','Southwestern Athletic Conference','Houston','Texas'),
('Texas State','Sun Belt Conference','San Marcos','Texas'),
('Texas Tech','Big 12 Conference','Lubbock','Texas'),
('The Citadel','Southern Conference','Charleston','South Carolina'),
('Toledo','Mid-American Conference','Toledo','Ohio'),
('Towson','Colonial Athletic Association','Towson','Maryland'),
('Troy','Sun Belt Conference','Troy','Alabama'),
('Tulane','American Athletic Conference','New Orleans','Louisiana'),
('Tulsa','American Athletic Conference','Tulsa','Oklahoma'),
('United States Air Force Academy','Mountain West Conference','Usafa','Colorado'),
('United States Military Academy','Patriot League','West Point','New York'),
('United States Naval Academy','Patriot League','Annapolis','Maryland'),
('Utah','Pacific-12 Conference','Salt Lake City','Utah'),
('Utah State','Mountain West Conference','Logan','Utah'),
('Utah Tech','Western Athletic Conference','Saint George','Utah'),
('Utah Valley','Western Athletic Conference','Orem','Utah'),
('Valparaiso','Missouri Valley Conference','Valparaiso','Indiana'),
('Vanderbilt','Southeastern Conference','Nashville','Tennessee'),
('Vermont','America East Conference','Burlington','Vermont'),
('Villanova','Big East Conference','Villanova','Pennsylvania'),
('Virginia','Atlantic Coast Conference','Charlottesville','Virginia'),
('Virginia Commonwealth','Atlantic 10 Conference','Richmond','Virginia'),
('Virginia Military Institute','Big South Conference','Lexington','Virginia'),
('Virginia Tech','Atlantic Coast Conference','Blacksburg','Virginia'),
('Wagner','Northeast Conference','Staten Island','New York'),
('Wake Forest','Atlantic Coast Conference','Winston-Salem','North Carolina'),
('Washington','Pacific-12 Conference','Seattle','Washington'),
('Washington State','Pacific-12 Conference','Pullman','Washington'),
('Weber State','Big Sky Conference','Ogden','Utah'),
('West Virginia','Big 12 Conference','Morgantown','West Virginia'),
('Western Carolina','Southern Conference','Cullowhee','North Carolina'),
('Western Illinois','Ohio Valley Conference','Macomb','Illinois'),
('Western Kentucky','Conference USA','Bowling Green','Kentucky'),
('Western Michigan','Mid-American Conference','Kalamazoo','Michigan'),
('Wichita State','American Athletic Conference','Wichita','Kansas'),
('William & Mary','Colonial Athletic Association','Williamsburg','Virginia'),
('Winthrop','Big South Conference','Rock Hill','South Carolina'),
('Wisconsin','Big Ten Conference','Madison','Wisconsin'),
('Wisconsin – Green Bay','Horizon League','Green Bay','Wisconsin'),
('Wisconsin – Milwaukee','Horizon League','Milwaukee','Wisconsin'),
('Wofford','Southern Conference','Spartanburg','South Carolina'),
('Wright State','Horizon League','Dayton','Ohio'),
('Wyoming','Mountain West Conference','Laramie','Wyoming'),
('Xavier','Big East Conference','Cincinnati','Ohio'),
('Yale','Ivy League','New Haven','Connecticut'),
('Youngstown State','Horizon League','Youngstown','Ohio')
